# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filerename.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_lwFileRenameDialog(object):
	def setupUi(self, lwFileRenameDialog):
		lwFileRenameDialog.setObjectName("lwFileRenameDialog")
		lwFileRenameDialog.resize(772, 889)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(lwFileRenameDialog.sizePolicy().hasHeightForWidth())
		lwFileRenameDialog.setSizePolicy(sizePolicy)
		lwFileRenameDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(lwFileRenameDialog)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.lwFileList = QtWidgets.QListWidget(lwFileRenameDialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lwFileList.sizePolicy().hasHeightForWidth())
		self.lwFileList.setSizePolicy(sizePolicy)
		self.lwFileList.setMaximumSize(QtCore.QSize(16777215, 120))
		self.lwFileList.setObjectName("lwFileList")
		self.verticalLayout_2.addWidget(self.lwFileList)
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.lwMvButton = QtWidgets.QPushButton(lwFileRenameDialog)
		self.lwMvButton.setEnabled(True)
		self.lwMvButton.setObjectName("lwMvButton")
		self.horizontalLayout_4.addWidget(self.lwMvButton)
		self.lwReload = QtWidgets.QPushButton(lwFileRenameDialog)
		self.lwReload.setObjectName("lwReload")
		self.horizontalLayout_4.addWidget(self.lwReload)
		self.lwOpenFile = QtWidgets.QPushButton(lwFileRenameDialog)
		self.lwOpenFile.setObjectName("lwOpenFile")
		self.horizontalLayout_4.addWidget(self.lwOpenFile)
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem)
		self.verticalLayout_2.addLayout(self.horizontalLayout_4)
		self.lwPathLine = QtWidgets.QPlainTextEdit(lwFileRenameDialog)
		self.lwPathLine.setMaximumSize(QtCore.QSize(16777215, 50))
		font = QtGui.QFont()
		font.setFamily("Liberation Mono")
		self.lwPathLine.setFont(font)
		self.lwPathLine.setReadOnly(True)
		self.lwPathLine.setObjectName("lwPathLine")
		self.verticalLayout_2.addWidget(self.lwPathLine)
		self.lwFilenameText = QtWidgets.QPlainTextEdit(lwFileRenameDialog)
		self.lwFilenameText.setMaximumSize(QtCore.QSize(16777215, 50))
		font = QtGui.QFont()
		font.setFamily("Liberation Mono")
		self.lwFilenameText.setFont(font)
		self.lwFilenameText.setReadOnly(True)
		self.lwFilenameText.setObjectName("lwFilenameText")
		self.verticalLayout_2.addWidget(self.lwFilenameText)
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.lwTypeCombo = QtWidgets.QComboBox(lwFileRenameDialog)
		self.lwTypeCombo.setMinimumSize(QtCore.QSize(100, 0))
		self.lwTypeCombo.setObjectName("lwTypeCombo")
		self.horizontalLayout.addWidget(self.lwTypeCombo)
		self.lwTypeInsert = QtWidgets.QPushButton(lwFileRenameDialog)
		self.lwTypeInsert.setEnabled(False)
		self.lwTypeInsert.setMinimumSize(QtCore.QSize(0, 0))
		self.lwTypeInsert.setMaximumSize(QtCore.QSize(23, 16777215))
		self.lwTypeInsert.setObjectName("lwTypeInsert")
		self.horizontalLayout.addWidget(self.lwTypeInsert)
		self.lwYearSpin = QtWidgets.QSpinBox(lwFileRenameDialog)
		self.lwYearSpin.setMinimumSize(QtCore.QSize(60, 0))
		self.lwYearSpin.setMaximumSize(QtCore.QSize(121, 16777215))
		self.lwYearSpin.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.lwYearSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
		self.lwYearSpin.setMinimum(1700)
		self.lwYearSpin.setMaximum(2100)
		self.lwYearSpin.setProperty("value", 1990)
		self.lwYearSpin.setObjectName("lwYearSpin")
		self.horizontalLayout.addWidget(self.lwYearSpin)
		self.lwYearInsert = QtWidgets.QPushButton(lwFileRenameDialog)
		self.lwYearInsert.setEnabled(False)
		self.lwYearInsert.setMinimumSize(QtCore.QSize(0, 0))
		self.lwYearInsert.setMaximumSize(QtCore.QSize(23, 16777215))
		self.lwYearInsert.setObjectName("lwYearInsert")
		self.horizontalLayout.addWidget(self.lwYearInsert)
		self.lwFiletypeCombo = QtWidgets.QComboBox(lwFileRenameDialog)
		self.lwFiletypeCombo.setMinimumSize(QtCore.QSize(100, 0))
		self.lwFiletypeCombo.setObjectName("lwFiletypeCombo")
		self.horizontalLayout.addWidget(self.lwFiletypeCombo)
		self.lwFiletypeInsert = QtWidgets.QPushButton(lwFileRenameDialog)
		self.lwFiletypeInsert.setEnabled(False)
		self.lwFiletypeInsert.setMaximumSize(QtCore.QSize(23, 16777215))
		self.lwFiletypeInsert.setObjectName("lwFiletypeInsert")
		self.horizontalLayout.addWidget(self.lwFiletypeInsert)
		spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem1)
		self.lwClearButton = QtWidgets.QPushButton(lwFileRenameDialog)
		self.lwClearButton.setObjectName("lwClearButton")
		self.horizontalLayout.addWidget(self.lwClearButton)
		self.verticalLayout_2.addLayout(self.horizontalLayout)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.lwMetaText = QtWidgets.QPlainTextEdit(lwFileRenameDialog)
		self.lwMetaText.setObjectName("lwMetaText")
		self.horizontalLayout_2.addWidget(self.lwMetaText)
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.lwParserText = QtWidgets.QPlainTextEdit(lwFileRenameDialog)
		font = QtGui.QFont()
		font.setFamily("Consolas")
		self.lwParserText.setFont(font)
		self.lwParserText.setObjectName("lwParserText")
		self.verticalLayout.addWidget(self.lwParserText)
		self.lwDebugText = QtWidgets.QPlainTextEdit(lwFileRenameDialog)
		self.lwDebugText.setMaximumSize(QtCore.QSize(16777215, 50))
		font = QtGui.QFont()
		font.setFamily("Liberation Mono")
		self.lwDebugText.setFont(font)
		self.lwDebugText.setObjectName("lwDebugText")
		self.verticalLayout.addWidget(self.lwDebugText)
		self.horizontalLayout_2.addLayout(self.verticalLayout)
		self.verticalLayout_2.addLayout(self.horizontalLayout_2)

		self.retranslateUi(lwFileRenameDialog)
		QtCore.QMetaObject.connectSlotsByName(lwFileRenameDialog)

	def retranslateUi(self, lwFileRenameDialog):
		_translate = QtCore.QCoreApplication.translate
		lwFileRenameDialog.setWindowTitle(_translate("lwFileRenameDialog", "generate document file name"))
		self.lwMvButton.setText(_translate("lwFileRenameDialog", "rename"))
		self.lwReload.setText(_translate("lwFileRenameDialog", "reload"))
		self.lwOpenFile.setText(_translate("lwFileRenameDialog", "open file"))
		self.lwTypeInsert.setText(_translate("lwFileRenameDialog", ">"))
		self.lwYearInsert.setText(_translate("lwFileRenameDialog", ">"))
		self.lwFiletypeInsert.setText(_translate("lwFileRenameDialog", ">"))
		self.lwClearButton.setText(_translate("lwFileRenameDialog", "clear"))

