# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lw_filerename.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_lwFileRenameDialog(object):
    def setupUi(self, lwFileRenameDialog):
        lwFileRenameDialog.setObjectName(_fromUtf8("lwFileRenameDialog"))
        lwFileRenameDialog.resize(772, 889)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lwFileRenameDialog.sizePolicy().hasHeightForWidth())
        lwFileRenameDialog.setSizePolicy(sizePolicy)
        lwFileRenameDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtGui.QVBoxLayout(lwFileRenameDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lwFileList = QtGui.QListWidget(lwFileRenameDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwFileList.sizePolicy().hasHeightForWidth())
        self.lwFileList.setSizePolicy(sizePolicy)
        self.lwFileList.setMaximumSize(QtCore.QSize(16777215, 120))
        self.lwFileList.setObjectName(_fromUtf8("lwFileList"))
        self.verticalLayout_2.addWidget(self.lwFileList)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lwMvButton = QtGui.QPushButton(lwFileRenameDialog)
        self.lwMvButton.setEnabled(True)
        self.lwMvButton.setObjectName(_fromUtf8("lwMvButton"))
        self.horizontalLayout_4.addWidget(self.lwMvButton)
        self.lwReload = QtGui.QPushButton(lwFileRenameDialog)
        self.lwReload.setObjectName(_fromUtf8("lwReload"))
        self.horizontalLayout_4.addWidget(self.lwReload)
        self.lwOpenFile = QtGui.QPushButton(lwFileRenameDialog)
        self.lwOpenFile.setObjectName(_fromUtf8("lwOpenFile"))
        self.horizontalLayout_4.addWidget(self.lwOpenFile)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.lwPathLine = QtGui.QPlainTextEdit(lwFileRenameDialog)
        self.lwPathLine.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.lwPathLine.setFont(font)
        self.lwPathLine.setReadOnly(True)
        self.lwPathLine.setObjectName(_fromUtf8("lwPathLine"))
        self.verticalLayout_2.addWidget(self.lwPathLine)
        self.lwFilenameText = QtGui.QPlainTextEdit(lwFileRenameDialog)
        self.lwFilenameText.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.lwFilenameText.setFont(font)
        self.lwFilenameText.setReadOnly(True)
        self.lwFilenameText.setObjectName(_fromUtf8("lwFilenameText"))
        self.verticalLayout_2.addWidget(self.lwFilenameText)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lwTypeCombo = QtGui.QComboBox(lwFileRenameDialog)
        self.lwTypeCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.lwTypeCombo.setObjectName(_fromUtf8("lwTypeCombo"))
        self.horizontalLayout.addWidget(self.lwTypeCombo)
        self.lwTypeInsert = QtGui.QPushButton(lwFileRenameDialog)
        self.lwTypeInsert.setEnabled(False)
        self.lwTypeInsert.setMinimumSize(QtCore.QSize(0, 0))
        self.lwTypeInsert.setMaximumSize(QtCore.QSize(23, 16777215))
        self.lwTypeInsert.setObjectName(_fromUtf8("lwTypeInsert"))
        self.horizontalLayout.addWidget(self.lwTypeInsert)
        self.lwYearSpin = QtGui.QSpinBox(lwFileRenameDialog)
        self.lwYearSpin.setMinimumSize(QtCore.QSize(60, 0))
        self.lwYearSpin.setMaximumSize(QtCore.QSize(121, 16777215))
        self.lwYearSpin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lwYearSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lwYearSpin.setMinimum(1700)
        self.lwYearSpin.setMaximum(2100)
        self.lwYearSpin.setProperty("value", 1990)
        self.lwYearSpin.setObjectName(_fromUtf8("lwYearSpin"))
        self.horizontalLayout.addWidget(self.lwYearSpin)
        self.lwYearInsert = QtGui.QPushButton(lwFileRenameDialog)
        self.lwYearInsert.setEnabled(False)
        self.lwYearInsert.setMinimumSize(QtCore.QSize(0, 0))
        self.lwYearInsert.setMaximumSize(QtCore.QSize(23, 16777215))
        self.lwYearInsert.setObjectName(_fromUtf8("lwYearInsert"))
        self.horizontalLayout.addWidget(self.lwYearInsert)
        self.lwFiletypeCombo = QtGui.QComboBox(lwFileRenameDialog)
        self.lwFiletypeCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.lwFiletypeCombo.setObjectName(_fromUtf8("lwFiletypeCombo"))
        self.horizontalLayout.addWidget(self.lwFiletypeCombo)
        self.lwFiletypeInsert = QtGui.QPushButton(lwFileRenameDialog)
        self.lwFiletypeInsert.setEnabled(False)
        self.lwFiletypeInsert.setMaximumSize(QtCore.QSize(23, 16777215))
        self.lwFiletypeInsert.setObjectName(_fromUtf8("lwFiletypeInsert"))
        self.horizontalLayout.addWidget(self.lwFiletypeInsert)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lwClearButton = QtGui.QPushButton(lwFileRenameDialog)
        self.lwClearButton.setObjectName(_fromUtf8("lwClearButton"))
        self.horizontalLayout.addWidget(self.lwClearButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lwMetaText = QtGui.QPlainTextEdit(lwFileRenameDialog)
        self.lwMetaText.setObjectName(_fromUtf8("lwMetaText"))
        self.horizontalLayout_2.addWidget(self.lwMetaText)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lwParserText = QtGui.QPlainTextEdit(lwFileRenameDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        self.lwParserText.setFont(font)
        self.lwParserText.setObjectName(_fromUtf8("lwParserText"))
        self.verticalLayout.addWidget(self.lwParserText)
        self.lwDebugText = QtGui.QPlainTextEdit(lwFileRenameDialog)
        self.lwDebugText.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.lwDebugText.setFont(font)
        self.lwDebugText.setObjectName(_fromUtf8("lwDebugText"))
        self.verticalLayout.addWidget(self.lwDebugText)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(lwFileRenameDialog)
        QtCore.QMetaObject.connectSlotsByName(lwFileRenameDialog)

    def retranslateUi(self, lwFileRenameDialog):
        lwFileRenameDialog.setWindowTitle(_translate("lwFileRenameDialog", "generate document file name", None))
        self.lwMvButton.setText(_translate("lwFileRenameDialog", "rename", None))
        self.lwReload.setText(_translate("lwFileRenameDialog", "reload", None))
        self.lwOpenFile.setText(_translate("lwFileRenameDialog", "open file", None))
        self.lwTypeInsert.setText(_translate("lwFileRenameDialog", ">", None))
        self.lwYearInsert.setText(_translate("lwFileRenameDialog", ">", None))
        self.lwFiletypeInsert.setText(_translate("lwFileRenameDialog", ">", None))
        self.lwClearButton.setText(_translate("lwFileRenameDialog", "clear", None))

